# Spring
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: kansou-ki
  config:
    import: 'aws-parameterstore:'

# Tomcat
server:
  servlet:
    context-path: /kansou-ki

# AWS
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-1

aws:
  paramstore:
    enabled: true
    region: ap-northeast-1
    prefix: /config
    profileSeparator: _
    failFast: true
